### ISSUE TITLE
Fidelity index includes TripNum = 0

### ISSUE THREAD

**Issue by cclatterbuck** [abfleishman/trakR#10]
MakeTrip() creates TripNum = 0, which is not really a trip but is time spent at the colony (for a central place forager). gilmour.fidelity() counts TripNum = 0 as a trip, which will add an additional "trip" in the fidelity index calculations which I think is extraneous. I can exclude TripNum=0 from the data, but perhaps the FI function should take this into account.

**Comment by abfleishman** [comment]
Nice catch!  The fidelity index should remove TripNum=="0"

**Comment by abfleishman** [comment]
@cclatterbuck I updated the fidelity example in the readme to remove the at colony "trips" (TripNum==0) but I left the function as is.  I think this is sufficient for now.
