### ISSUE TITLE
InOutPoints notes

### ISSUE THREAD

**Issue by mgilmour** [abfleishman/trakR#4]
- [x]  "Error in plot.window(...) : need finite 'xlim' values". This is a common error when plotting via R-Studio & Windows. I forgot how to fix it, but should be addressed.
- [x]  Need to note that the date column in "tracks" dataframe needs to be named "datetime" otherwise there's an error.
- [x]  "zoo" pkg needs to be installed/loaded (in function script?) in order to use rollmean().

**Comment by abfleishman** [comment]
Added package imports

**Comment by abfleishman** [comment]
added a datetime column name as param
